config/routes.rb
Rails.application.routes.draw do
  authenticate :user do
    scope(path: :cp) do
      resources :blogs
    end
  end

  root to: 'home#index'
  get 'blogs/:id', to: 'home#show', as: 'home_show'
  get 'about', to: 'home#about', as: 'about'
  get 'contact', to: 'home#contact', as: 'contact'

  devise_for :users, skip: :registration
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
  has_rich_text :content
  has_rich_text :description
  has_one_attached :featured_image do |attachable|
    attachable.variant :small_square, resize_to_fill: [300, 300]
    attachable.variant :large, resize_to_limit: [600, 875]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # devise :database_authenticatable, :registerable,
  #        :recoverable, :rememberable, :validatable
  devise :database_authenticatable, :rememberable, :validatable

  has_many :blogs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: %i[ show edit update destroy ]

  # GET /blogs or /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1 or /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs or /blogs.json
  def create
    @blog = current_user.blogs.create(blog_params)

    respond_to do |format|
      if @blog.persisted?
        format.html { redirect_to blog_url(@blog), notice: "Blog was successfully created." }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1 or /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to blog_url(@blog), notice: "Blog was successfully updated." }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1 or /blogs/1.json
  def destroy
    @blog.destroy!

    respond_to do |format|
      format.html { redirect_to blogs_url, notice: "Blog was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blog_params
      params.require(:blog).permit(:title, :content, :featured_image, :description, :published)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @blogs = Blog.where('published < ?', Time.current )
  end

  def show
    @blog = Blog.find(params[:id])
  end

  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/blogs/_blog.html.erb
<div id="<%= dom_id blog %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">User:</strong>
    <%= blog.user_id %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Title:</strong>
    <%= blog.title %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Content:</strong>
    <%= blog.content %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Featured image:</strong>
    <%= link_to blog.featured_image.filename, blog.featured_image if blog.featured_image.attached? %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Description:</strong>
    <%= blog.description %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Published:</strong>
    <%= blog.published %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this blog", blog, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Edit this blog", edit_blog_path(blog), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/blogs/_form.html.erb
<%= form_with(model: blog, class: "contents") do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
        <% blog.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :title %>
    <%= form.text_field :title, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5 prose">
    <%= form.label :content %>
    <%= form.rich_text_area :content, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :featured_image %>
    <%= form.file_field :featured_image, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5 prose">
    <%= form.label :description %>
    <%= form.rich_text_area :description, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :published %>
    <%= form.datetime_field :published, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<%= render(Layout::AppComponent.new) do %>
  <div class="mx-auto md:w-2/3 w-full">
    <h1 class="font-bold text-4xl">Editing blog</h1>

    <%= render "form", blog: @blog %>

    <%= link_to "Show this blog", @blog, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Back to blogs", blogs_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
<% end %>

app/views/blogs/index.html.erb
<%= render(Layout::AppComponent.new) do%>
  <div class="w-full">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <div class="flex justify-between items-center">
      <h1 class="font-bold text-4xl">Blogs</h1>
      <%= link_to "New blog", new_blog_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
    </div>

    <div id="blogs" class="min-w-full">
      <%= render @blogs %>
    </div>
  </div>
<% end %>

app/views/blogs/new.html.erb
<%= render(Layout::AppComponent.new) do %>
  <div class="mx-auto md:w-2/3 w-full">
    <h1 class="font-bold text-4xl">New blog</h1>

    <%= render "form", blog: @blog %>

    <%= link_to "Back to blogs", blogs_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
<% end %>

app/views/blogs/show.html.erb
<%= render(Layout::AppComponent.new) do %>
  <div class="mx-auto md:w-2/3 w-full flex">
    <div class="mx-auto">
      <% if notice.present? %>
        <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
      <% end %>

      <%= render @blog %>

      <%= link_to "Edit this blog", edit_blog_path(@blog), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      <div class="inline-block ml-2">
        <%= button_to "Destroy this blog", blog_path(@blog), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
      </div>
      <%= link_to "Back to blogs", blogs_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    </div>
  </div>
<% end %>

app/views/home/about.html.erb
<%= render(Layout::AppComponent.new) do %>
  <div>
    <section class="flex max-w-screen-md mx-auto">
      This is just a blog. I'm not sure why I have an about. Its another thing to link I guess...
    </section>
  </div>
<% end %>

app/views/home/contact.html.erb
<%= render(Layout::AppComponent.new) do %>
  <div>
    <section class="flex max-w-screen-md mx-auto">
      I don't actually want you to contact me :)
    </section>
  </div>
<% end %>

app/views/home/index.html.erb
<%= render(Layout::AppComponent.new) do %>
  <div>
    <% @blogs.each do |blog| %>
      <section class="flex border rounded-xl max-w-screen-lg mx-auto">
        <%= image_tag blog.featured_image.variant(:small_square), class: 'rounded-tl-xl rounded-bl-xl' %>
        <div class="p-8">
          <h3 class="text-xl font-bold">
            <%= link_to home_show_path(blog) do %>
              <%= blog.title %>
            <% end %>
          </h3>
          <div class="prose">
            <%= blog.description %>
          </div>
        </div>
      </section>
    <% end %>
  </div>
<% end %>

app/views/home/show.html.erb
<%= render(Layout::AppComponent.new) do %>
  <div>
    <section class="flex max-w-screen-md mx-auto">
      <div class="p-8">
        <h2 class="text-2xl font-bold">
          <%= @blog.title %>
        </h2>
        <%= image_tag @blog.featured_image.variant(:large) %>
        <div class="prose">
          <%= @blog.content %>
        </div>
      </div>
    </section>
  </div>
<% end %>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mymango</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main>
      <%= yield %>
    </main>
  </body>
</html>